language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      
jdk:
  - oraclejdk8
  
service:
  - mysql

script:
        - cd $TRAVIS_BUILD_DIR/guestbook
        - mvn test

notifications:
  email: false
